version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
    - .docker/db-data:/data/db
    env_file:
      - .env
  app:
    build:
      dockerfile: Dockerfile
    container_name: shortner
    env_file:
      - .env
    ports:
      - 8080:8080